---
- hosts: all
  become: true
  tasks:
  - name: Copy dtn deployment file
    copy:
        src: ./dtn.yaml
        dest: /home/vagrant/dtn.yaml

  - name: Create dtn namespace
    become: False
    command: kubectl create ns process-dtn

  - name: Wait 5s
    become: False
    command: sleep 5

  - name: Deploy dtn node
    become: False
    command: kubectl create -f dtn.yaml

  - name: Wait for dtn node up
    become: False
    command: kubectl wait -n process-dtn --for=condition=Ready pod/core-dtn --timeout=360s
