apiVersion: v1
kind: Service
metadata:
  name: dtn
  namespace: process-dtn
spec:
  selector:
    name: core-dtn
  ports:
  - port: 22
    targetPort: 22
---
apiVersion: v1
kind: Pod
metadata:
  namespace: process-dtn
  name: core-dtn
  labels:
    name: core-dtn
spec:
  hostname: dtn
  containers:
    - name: core-dtn
      image: microinfrastructure/sshd:default
      env:
        - name: SSH_ENABLE_PASSWORD_AUTH
          value: "true"
      ports:
        - containerPort: 22

